pcpath: /root/p2m/data/guitar.ply
initmeshpath: /root/p2m/data/guitar_initmesh.obj
savepath: /root/p2m/checkpoints/guitar

bfs_depth: 0
# faces_to_part: [8000, 16000, 20000]


## model parameters
in_channel: 6
convs: [16, 32, 64, 64, 128]
pools: [0.0, 0.0, 0.0, 0.0]
res_blocks: 3
transfer: True
leaky: 0.01 ## slope for leaky relu
init_weights: 0.002

learning_rate: 1.1e-4
iters: 10000

thres: 0.99

samples: 25000
start_samples: 15000
upsample: 1000
slope: 0.8